spring.application.name=getra
server.servlet.context-path=/getra/api/
spring.mvc.problemdetails.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://ep-icy-feather-aha94w87-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6InBElL9gGmW

springdoc.override-with-generic-response=false
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:true}

app.cors.allow-credentials=false
app.cors.allowed-origins=*
app.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
app.cors.allowed-headers=*